# Default values for overrides-sync
# This is a YAML-formatted file.

# Mimir configuration
mimir:
  namespace: "mimir"
  overridesConfigMap: "mimir-overrides"

# RLS configuration
rls:
  host: "mimir-rls.mimir-edge-enforcement.svc.cluster.local"
  adminPort: "8082"

# Controller configuration
pollFallbackSeconds: 30

# Service configuration
service:
  type: ClusterIP
  port: 9090

# Logging configuration
log:
  level: "info"

# Deployment configuration
replicaCount: 1

image:
  repository: ghcr.io/AkshayDubey29/overrides-sync
  tag: "latest"
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  capabilities:
    drop:
      - ALL

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

# Horizontal Pod Autoscaler
# Note: HPA is not recommended for overrides-sync as it's a single ConfigMap watcher.
# Multiple replicas watching the same ConfigMap create duplicate work and require leader election.
hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Pod Disruption Budget
# Recommended for production to ensure availability during node maintenance
pdb:
  enabled: false  # Enable in production with replicaCount: 2
  minAvailable: 1
  # maxUnavailable: 1

# Network Policy
networkPolicy:
  enabled: true

# Service Monitor for Prometheus
serviceMonitor:
  enabled: false
  interval: 30s
  scrapeTimeout: 10s

# Additional environment variables
env: []

# Additional volume mounts
volumeMounts: []

# Additional volumes
volumes: [] 