apiVersion: v1
kind: ConfigMap
metadata:
  name: mimir-overrides
  namespace: default
data:
  # Boltx tenant configuration matching Mimir global limits
  boltx: |
    {
      "samples_per_second": 0,
      "burst_pct": 0,
      "max_body_bytes": 0,
      "max_labels_per_series": 50,
      "max_label_value_length": 2048,
      "max_series_per_request": 20000000,
      "enforcement": {
        "enabled": true,
        "enforce_samples_per_second": false,
        "enforce_max_body_bytes": false,
        "enforce_max_labels_per_series": true,
        "enforce_max_series_per_request": true,
        "enforce_bytes_per_second": false
      }
    }
