# Minimal Envoy configuration for resource-constrained kind cluster

# Resource configuration - Ultra minimal
replicaCount: 1  # Only 1 replica for testing

resources:
  limits:
    cpu: 200m    # Ultra-minimal CPU limit
    memory: 128Mi  # Ultra-minimal memory limit
  requests:
    cpu: 50m     # Ultra-minimal CPU request
    memory: 32Mi   # Ultra-minimal memory request

# Buffer configuration - Minimal for testing
bufferLimits:
  maxRequestBytes: 1048576    # 1MB limit
  bufferMaxBytes: 1048576     # 1MB limit

# HTTP/2 configuration - Minimal
http2ProtocolOptions:
  initialStreamWindowSize: 1048576      # 1MB
  initialConnectionWindowSize: 1048576  # 1MB

# RLS fallback configuration
rlsFallback:
  enabled: true
  logFallbackEvents: true

# Health check configuration - Very lenient
healthCheck:
  livenessProbe:
    httpGet:
      path: /ready
      port: 8080
    initialDelaySeconds: 120
    periodSeconds: 120
    timeoutSeconds: 30
    failureThreshold: 10
  readinessProbe:
    httpGet:
      path: /ready
      port: 8080
    initialDelaySeconds: 120
    periodSeconds: 120
    timeoutSeconds: 30
    failureThreshold: 10
