# Envoy Proxy Values - Production Configuration
# Use this file for deploying Envoy in production with optimized settings

# Deployment configuration
replicaCount: 1

nameOverride: ""
fullnameOverride: ""

# Service configuration
service:
  port: 8080
  type: ClusterIP
  annotations: {}

# Remote write configuration
remoteWrite:
  path: "/api/v1/push"

# Tenant identification
tenantHeader: "X-Scope-OrgID"

# Mimir distributor configuration
mimir:
  distributorHost: "mock-mimir-distributor.mimir.svc.cluster.local"
  distributorPort: 8080

# RLS service configuration
rls:
  host: "mimir-rls.default.svc.cluster.local"
  extAuthzPort: 8080
  rateLimitPort: 8081

# External authorization configuration - ULTRA OPTIMIZED
extAuthz:
  maxRequestBytes: 5242880   # 5 MiB - Reduced for faster processing
  failureModeAllow: true     # Allow on failure for maximum throughput
  timeout: "1s"              # Ultra-fast timeout
  disableBodyParsing: false  # Keep body parsing for limits
  
  # Buffer settings for ultra-fast processing
  bufferMaxBytes: "10485760"       # 10MB buffer for faster processing
  bufferTimeout: "2s"              # Ultra-fast buffer timeout
  
  # Retry configuration - Ultra-fast
  retryOn: "connect-failure,unavailable"  # Minimal retry conditions
  numRetries: 0                    # No retries for ultra-fast fail
  retryBackoffBaseInterval: "50ms" # Ultra-fast retry interval
  
  # Performance optimizations - Ultra-fast
  includePeerCertificate: false    # Disable for performance
  includeTlsSession: false         # Disable for performance

# Rate limiting configuration - ULTRA OPTIMIZED
rateLimit:
  failureModeDeny: false    # Allow requests when rate limit service fails
  domain: "mimir_remote_write"
  grpcTimeout: "1s"         # Ultra-fast timeout
  timeout: "500ms"          # Ultra-fast timeout

# Proxy configuration - ULTRA OPTIMIZED
proxy:
  upstreamTimeout: "10s"  # Ultra-fast timeout for metric payloads
  httpProtocol:
    acceptHttp10: true
    useRemoteAddress: true
    xffNumTrustedHops: 1

# Load balancing configuration - ULTRA OPTIMIZED
loadBalancer:
  policy: "least_request"        # Least request for better distribution
  healthCheck:
    enabled: true
    interval: "5s"               # Faster health checks
    timeout: "1s"                # Faster timeout
    unhealthyThreshold: 2        # Faster failure detection
    healthyThreshold: 1          # Faster recovery

# Logging configuration - ULTRA OPTIMIZED
logging:
  level: "warn"                  # Minimal logging for maximum performance
  enableAccessLogs: false        # Disable access logs for performance
  enableDebugLogs: false         # Disable debug logging for performance
  enableDetailedLogs: false      # Disable detailed logs for performance

# Resource limits and overload management
resourceLimits:
  maxHeapSizeBytes: 402653184  # 384 MiB (75% of 512Mi container limit)
  shrinkHeapThreshold: 0.8     # Start shrinking heap at 80%
  heapStopAcceptingThreshold: 0.95  # Stop accepting at 95% heap

# Image configuration
image:
  repository: ghcr.io/akshaydubey29/mimir-envoy
  tag: "latest"
  pullPolicy: IfNotPresent

# Image pull secrets
imagePullSecrets: []

# Service Account
serviceAccount:
  create: true
  annotations: {}
  name: ""

# Pod annotations - Production
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "9901"
  prometheus.io/path: "/stats/prometheus"

# Pod security context
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000

# Security context
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  capabilities:
    drop:
      - ALL

# Resource configuration - Production
resources:
  limits:
    cpu: 2000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

# Node selector
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity
affinity: {}

# Horizontal Pod Autoscaler
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Pod Disruption Budget
pdb:
  enabled: true
  minAvailable: 1

# Service Monitor for Prometheus - Production
serviceMonitor:
  enabled: true   # Production: Enable for monitoring
  interval: 30s
  scrapeTimeout: 10s
  labels: {}
  annotations: {}

# ConfigMap configuration
configMap:
  create: true

# Volume mounts and volumes
volumeMounts: []
volumes: []
