# Overrides-Sync Values with Real-Time Synchronization
# Use this file for deploying Overrides-Sync with real-time updates

# Deployment configuration
replicaCount: 1

nameOverride: ""
fullnameOverride: ""

# Image configuration
image:
  repository: ghcr.io/akshaydubey29/overrides-sync
  tag: "latest-dual-limits-arm64"
  pullPolicy: IfNotPresent

# Service configuration
service:
  type: ClusterIP
  port: 9090  # 🔧 FIX: Match the default metrics port in the application
  annotations: {}

# 🔧 OPTIMIZED: Enhanced resource configuration for real-time sync
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Security context
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65532
  capabilities:
    drop:
      - ALL

# Pod security context
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 65532
  fsGroup: 65532

# 🔧 OPTIMIZED: Pod annotations for real-time sync
podAnnotations:
  debug: "true"
  logging: "debug"
  sync_debug: "true"
  real_time_sync: "true"

# Node selector
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity
affinity: {}

# Service Account
serviceAccount:
  create: true
  annotations: {}

# RBAC configuration
rbac:
  create: true
  rules:
    - apiGroups: [""]
      resources: ["configmaps"]
      verbs: ["get", "list", "watch"]
    - apiGroups: [""]
      resources: ["events"]
      verbs: ["create", "patch"]

# 🔧 OPTIMIZED: Enhanced logging configuration for real-time sync
log:
  level: "debug"  # Set to debug for troubleshooting
  format: "json"

# Controller configuration
mimir:
  namespace: "mimir"
  overridesConfigMap: "mimir-overrides"

rls:
  host: "mimir-rls.mimir-edge-enforcement.svc.cluster.local"
  adminPort: "8082"

# 🔧 OPTIMIZED: Real-time polling configuration for immediate updates
pollFallbackSeconds: 2  # 🔧 FIX: Reduced to 2s for near real-time updates

# 🔧 OPTIMIZED: Additional environment variables for real-time sync
env:
  - name: DEBUG
    value: "true"
  - name: LOG_LEVEL
    value: "debug"
  - name: SYNC_DEBUG
    value: "true"
  - name: REAL_TIME_SYNC
    value: "true"

# 🔧 OPTIMIZED: Enhanced liveness and readiness probes for real-time sync
livenessProbe:
  httpGet:
    path: /healthz
    port: metrics
  initialDelaySeconds: 10  # 🔧 OPTIMIZED: Reduced from 30s to 10s
  periodSeconds: 10        # 🔧 OPTIMIZED: Reduced from 30s to 10s
  timeoutSeconds: 5        # 🔧 OPTIMIZED: Reduced from 10s to 5s
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /healthz
    port: metrics
  initialDelaySeconds: 5   # 🔧 OPTIMIZED: Reduced from 10s to 5s
  periodSeconds: 5         # 🔧 OPTIMIZED: Reduced from 10s to 5s
  timeoutSeconds: 3        # 🔧 OPTIMIZED: Reduced from 5s to 3s
  failureThreshold: 3

# Startup probe
startupProbe:
  httpGet:
    path: /healthz
    port: metrics
  initialDelaySeconds: 5   # 🔧 OPTIMIZED: Reduced from 10s to 5s
  periodSeconds: 5         # 🔧 OPTIMIZED: Reduced from 10s to 5s
  timeoutSeconds: 3        # 🔧 OPTIMIZED: Reduced from 5s to 3s
  failureThreshold: 10     # 🔧 OPTIMIZED: Reduced from 30 to 10

# Horizontal Pod Autoscaler
hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Pod Disruption Budget
pdb:
  enabled: true
  minAvailable: 1

# Service Monitor for Prometheus
serviceMonitor:
  enabled: false
  interval: 10s            # 🔧 OPTIMIZED: Reduced from 30s to 10s
  scrapeTimeout: 5s        # 🔧 OPTIMIZED: Reduced from 10s to 5s
  labels: {}
  annotations: {}

# Image pull secrets
imagePullSecrets: []

# 🔧 OPTIMIZED: Network Policy for real-time sync access
networkPolicy:
  enabled: true
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            name: monitoring
      ports:
      - protocol: TCP
        port: 8080
  egress:
    - to:
      - namespaceSelector:
          matchLabels:
            name: mimir
      ports:
      - protocol: TCP
        port: 443
    - to:
      - namespaceSelector:
          matchLabels:
            name: mimir-edge-enforcement
      ports:
      - protocol: TCP
        port: 8082
    - to: []  # Allow DNS resolution
      ports:
      - protocol: UDP
        port: 53

# 🔧 OPTIMIZED: Additional configuration for real-time sync
config:
  # Real-time mode
  realTimeSync: true
  
  # Enhanced error reporting
  errorReporting: true
  
  # Detailed logging
  detailedLogging: true
  
  # Connection pooling (already configured in controller)
  connectionPooling: true
  
  # 🔧 OPTIMIZED: Real-time sync settings
  sync:
    watchTimeout: "5s"           # 🔧 OPTIMIZED: Reduced from 30s to 5s
    retryDelay: "1s"             # 🔧 OPTIMIZED: Reduced from 5s to 1s
    maxRetries: 3                # 🔧 OPTIMIZED: Reduced from 5 to 3
    batchSize: 10                # 🔧 OPTIMIZED: Process tenants in batches
    parallelSync: true           # 🔧 OPTIMIZED: Enable parallel tenant sync
