# RLS (Rate Limit Service) Values - Production Configuration
# Use this file for deploying RLS in production with optimized settings

# Service configuration
service:
  type: ClusterIP
  port: 8082  # Main service port (admin API)
  ports:
    extAuthz: 8080
    rateLimit: 8081
    admin: 8082
    metrics: 9090

# Tenant identification
tenantHeader: "X-Scope-OrgID"

# Limits configuration - Production
limits:
  maxRequestBytes: "10485760"  # 10 MiB - Increased for large Alloy payloads
  maxBodyBytes: 0              # 0 means no default body size cap
  failureModeAllow: true       # Production: Allow requests when parsing fails (with limit enforcement)
  defaultSamplesPerSecond: 1000  # Production: Conservative default rate limit
  defaultBurstPercent: 0.1     # Production: Conservative burst allowance
  enforceBodyParsing: true     # Production: Enable body parsing for limit enforcement
  defaultMaxLabelsPerSeries: 60
  defaultMaxLabelValueLength: 2048
  defaultMaxSeriesPerRequest: 100000

# Store configuration
store:
  backend: "memory"  # memory or redis

# Logging configuration - Production
log:
  level: "info"  # Production: Info level for performance
  enableGRPCLogs: false  # Production: Disable gRPC logs for performance
  enableDetailedLogs: false  # Production: Disable detailed logs for performance

# Deployment configuration
replicaCount: 1

image:
  repository: ghcr.io/akshaydubey29/mimir-rls
  tag: "latest-limits-fix"  # Production: Use the latest limits-fix image
  pullPolicy: IfNotPresent  # Production: Use IfNotPresent for efficiency

# Resource configuration - Production
resources:
  limits:
    cpu: 2000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 512Mi

# Security context
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  capabilities:
    drop:
      - ALL

# Horizontal Pod Autoscaler
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Pod Disruption Budget
pdb:
  enabled: true
  minAvailable: 1

# Service Account
serviceAccount:
  create: true
  annotations: {}

# Pod annotations - Production
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "9090"
  prometheus.io/path: "/metrics"

# Node selector
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity
affinity: {}

# Service Monitor for Prometheus - Production
serviceMonitor:
  enabled: true   # Production: Enable for monitoring
  interval: 30s
  scrapeTimeout: 10s
  labels: {}
  annotations: {}

# Image pull secrets
imagePullSecrets: []
