# Minimal RLS configuration for Kind cluster testing
replicaCount: 1

# Reduced resource configuration for Kind cluster
resources:
  limits:
    cpu: 500m     # 0.5 core limit
    memory: 512Mi # 512MB memory limit
  requests:
    cpu: 50m      # 50m CPU request
    memory: 64Mi  # 64MB memory request

# Keep the production limits configuration
limits:
  maxRequestBytes: 52428800    # 50 MiB - Production: Increased for 5M series
  maxBodyBytes: 52428800       # 50 MiB - Production: Maximum body size per request
  failureModeAllow: true       # Production: Allow requests when parsing fails
  defaultSamplesPerSecond: 10000     # 10K samples/sec - Production: Increased for 5M series
  defaultBurstPercent: 50      # 50% burst allowance - Production: More burst capacity
  enforceBodyParsing: true     # Production: Enable body parsing for cardinality analysis
  defaultMaxLabelsPerSeries: 20      # Production: Increased label limit
  defaultMaxLabelValueLength: 4096   # Production: Increased label value length
  defaultMaxSeriesPerRequest: 100000 # Production: 100K series per request for 5M total

# Keep other configurations
enforcement:
  enabled: true
  enforceMaxSeriesPerRequest: true
  enforceMaxSeriesPerMetric: true
  enforceMaxLabelsPerSeries: true
  enforceSamplesPerSecond: true
  enforceBytesPerSecond: false
  enforceMaxBodyBytes: true

# Store configuration - Use memory for minimal setup
store:
  backend: "memory"

# Redis configuration - Disabled for minimal setup
redis:
  enabled: false

mimir:
  host: "mimir-distributor.mimir.svc.cluster.local"
  port: "8080"

tenantHeader: "X-Scope-OrgID"
