apiVersion: v1
kind: Service
metadata:
  name: {{ include "overrides-sync.fullname" . }}
  labels:
    {{- include "overrides-sync.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    {{- include "overrides-sync.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.service.port }}
      targetPort: metrics

