apiVersion: v2
name: admin-ui
description: Admin UI for Mimir Edge Enforcement monitoring and management
type: application
version: 0.1.0
appVersion: "1.0.0"
icon: https://raw.githubusercontent.com/grafana/mimir/main/docs/sources/mimir/logo.svg
keywords:
  - mimir
  - admin-ui
  - monitoring
  - dashboard
  - react
home: https://github.com/AkshayDubey29/mimir-edge-enforcement
sources:
  - https://github.com/AkshayDubey29/mimir-edge-enforcement
maintainers:
  - name: AkshayDubey29
    email: akshay.dubey29@gmail.com
